#Windows環境
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password: <%= ENV['DATABASE_PASSWORD'] %>

#Centos環境
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   socket: /var/lib/mysql/mysql.sock

#mac環境
default: &default
 adapter: mysql2
 encoding: utf8
 pool: 5
 username: root
 password:
 socket: /tmp/mysql.sock

development:
  <<: *default
  database: tech-share_development

test:
  <<: *default
  database: tech-share_test

production:
  <<: *default
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  host: tech-share-web.cr44stouhopx.ap-northeast-1.rds.amazonaws.com
  database: tech-share_production
  username: root
  password: <%= Rails.application.credentials[:database][:password] %>
